openapi: "3.0.0"
info:
  title: "Wutsi Marketplace Manager API"
  description: Marketplace Business Layer
  version: "1.0.0"

servers:
  - url: https://marketplace-manager-test.herokuapp.com
    description: Sandbox
  - url: https://marketplace-manager-prod.herokuapp.com
    description: Production

paths:
  /v1/stores:
    post:
      operationId: "enable-store"
      description: Enable the store of the current user
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnableStoreResponse'
      tags:
        - Store

    delete:
      operationId: "suspend-store"
      description: Disable the store of the current user
      responses:
        200:
          description: Success
      tags:
        - Store


  /v1/products:
    post:
      operationId: create-product
      description: Add product into the current user's store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProductResponse'
      tags:
        - Product

  /v1/products/attributes:
    post:
      operationId: update-product-attribute
      description: Update an attribute of the product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductAttributeRequest'
      responses:
        200:
          description: Success
      tags:
        - Product

  /v1/products/status:
    post:
      operationId: update-product-status
      description: Update the status of a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductStatusRequest'
      responses:
        200:
          description: Success
      tags:
        - Product


  /v1/pictures:
    post:
      operationId: add-picture
      description: Add a picture to a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddPictureRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddPictureResponse'
      tags:
        - Product

  /v1/pictures/{id}:
    delete:
      operationId: delete-picture
      description: Delete a picture to a product
      parameters:
        - in: path
          name: id
          description: ID of the picture
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Success
      tags:
        - Product


  /v1/categories/import:
    get:
      operationId: "import-category"
      description: |
        Import all the product categories.
        Wutsi used [Google Product Categories](https://support.google.com/merchants/answer/6324436) for categorizing products
      parameters:
        - in: query
          name: language
          description: 2 letter code of the language of the categories
          required: true
          schema:
            type: string
            required: true
      responses:
        200:
          description: Success
      tags:
        - Category


components:
  schemas:
    EnableStoreResponse:
      type: object
      properties:
        storeId:
          type: integer
          format: int64
          description: ID of the store

    CreateProductRequest:
      type: object
      properties:
        pictureUrl:
          type: string
          description: Product title
        categoryId:
          type: integer
          format: int64
          nullable: true
        title:
          type: string
          description: Product title
          nullable: true
        summary:
          type: string
          description: Product summary
          nullable: true
        price:
          type: integer
          format: int64
          description: Price of the product
          nullable: true
      required:
        - pictureUrl

    CreateProductResponse:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          description: ID of the product created

    UpdateProductAttributeRequest:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          description: ID of the product to update
        name:
          type: string
          description: Name of the attribute
        value:
          type: string
          description: Value of the attribute
          nullable: true
      required:
        - name

    UpdateProductStatusRequest:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          description: ID of the product to update
        status:
          type: string
          description: Name of the attribute
          enum:
            - DRAFT
            - PUBLISHED
      required:
        - status

    AddPictureRequest:
      type: object
      properties:
        productId:
          type: integer
          format: int64
          description: ID of the product
        url:
          type: string
          description: URL of the picture
      required:
        - url

    AddPictureResponse:
      type: object
      properties:
        pictureId:
          type: integer
          format: int64
          description: ID of the picture
